### ISSUE TITLE
Pandera DataFrame support

### ISSUE THREAD

**Issue by Girmii** [microsoft/vscode-data-wrangler#317]
## Environment data

-   VS Code version: 1.94.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.12.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.9.1
-   Python Extension version (available under the Extensions sidebar): v2024.16.1
-   OS (Windows | Mac | Linux distro) and version: Windows Subsystem for Linux - Ubuntu 20.04
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: 3.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

[Pandera](https://pandera.readthedocs.io/en/stable/) is a framework to perform data validation/sanitation on Pandas DataFrames, similar to Pydantic for dataclasses.
Validation can be performed by casting a Pandas DataFrame to the Pandera DataFrame subclass.
As the Pandera DataFrame is a subclasses of the Pandas Dataframe, it should support all functionality of Pandas DataFrames and thus Data Wrangler should also be able to process them.

## Actual behaviour
When trying to inspect a Pandera DataFrame with Data Wrangler the following error comes up:

```
Type 'pandera.typing.pandas.DataFrame' is not currently supported in Data Wrangler. Please open a feature request on the Data Wrangler GitHub repository.
```

## Steps to reproduce:

```python
import pandas as pd
import pandera as pa
from pandera.typing import DataFrame


class ExampleModel(pa.DataFrameModel):
    pass

A = pd.DataFrame(["a", "b", "c"])

B = DataFrame[ExampleModel](A)
```

One way to bypass the problem is to cast the Pandera DataFrame back to a Pandas DataFrame, after which it can be inspected with Data Wrangler. However, this is quite cumbersome to do every time you want to inspect a Pandera DataFrame.

```python
C = pd.DataFrame(B)
```

**Comment by crashdomi** [comment]
feature would be highly appreciated!

**Comment by pwang347** [comment]
Hi @Girmii, @crashdomi - just wanted to share that we've just released a change in pre-release version 1.13.2 which should allow this conversion to happen automatically. Please feel free to give it a try and let us know if you have any feedback. Cheers!

**Comment by pwang347** [comment]
Hi @Girmii, apologies for the delayed response. Is this happening still with the same DataFrame above or are you trying a different one?

```python
import pandas as pd
import pandera as pa
from pandera.typing import DataFrame


class ExampleModel(pa.DataFrameModel):
    pass

A = pd.DataFrame(["a", "b", "c"])

B = DataFrame[ExampleModel](A)
B # <- breakpoint here
```

The above loads for me with debugpy (in a .py file):
![Image](https://github.com/user-attachments/assets/1aaaa94c-0c33-45cc-8598-2e61c9a9d06a)

The initial message about compatibility above is expected, as we've added support now using fallback converters. Do you have any debug config such as `PYDEVD_INTERRUPT_THREAD_TIMEOUT` that is terminating the execution early? (from logs, it seems like ~3s in)

**Comment by Girmii** [comment]
Thanks for getting back to me. You are indeed right that is was a different data frame. For the example above it now works correctly.

However, if we increase the data size a bit, the error I mentioned above comes up;
```python
import numpy as np
import pandas as pd
import pandera as pa
from pandera.typing import DataFrame


class ExampleModel(pa.DataFrameModel):
    pass


data = np.random.randint(low=0, high=100, size=(800, 100))
A = pd.DataFrame(data)

B = DataFrame[ExampleModel](A)

print(B.shape)
```
Even when I increase the `PYDEVD_INTERRUPT_THREAD_TIMEOUT` value to 60s, it still won't complete successfully, producing an additional error: `Failed to update data frame: Received malformed content: eyboardInterrupt()

**Comment by pwang347** [comment]
Hi @Girmii, thank you very much for the repro! I can confirm that this behaviour is unintended (800x100 is way too small for this to lag), and seems like we can fix this on our side. Will let you know once this fix is released. Cheers!

**Comment by pwang347** [comment]
Hi @Girmii, just wanted to provide an update that this issue should now be fixed in pre-release version 1.13.3 - please try this again and let me know if you're still running into performance issues!

**Comment by Girmii** [comment]
Checked out 1.13.3 and it seems to work well, also for even larger dataframe sizes. Thanks for the effort!
