### ISSUE TITLE
Feature request: support for GeoDataFrame

### ISSUE THREAD

**Issue by rmpIGN** [microsoft/vscode-data-wrangler#386]
It would be great if Data Wrangler had support for GeoDataFrame objects so we could interact with a map to visualize our geodata. It could be something similar to what the GeoDataFrame.explore() method renders : https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html

Thanks !

**Comment by pwang347** [comment]
Hi @remipIGN, thank you for the feature request! We've added it to the backlog and will let you know of any updates. This also seems to be the same request as https://github.com/microsoft/vscode-data-wrangler/issues/369, but seeing as there is a bit more traction on this one (and some more details) I'll consolidate the issues to this one.

Hope this helps!

**Comment by simonhuwiler** [comment]
In the latest Data Wrangler version, GeoPandas throws an error as soon as a geodata frame is displayed. Of course, this is a bit troublesome if you want to use Data Wrangler with Pandas, but also work on Geopandas projects at the same time. I currently have to deactivate the plugin depending on the project.

```
df = gpd.read_file('countries.geojson')
df.head()
```
Error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Documents/projects/visuals-sommer-winterzeit-analyse/env/lib/python3.12/site-packages/IPython/core/formatters.py:402, in BaseFormatter.__call__(self, obj)
    [400](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:400)     pass
    [401](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:401) else:
--> [402](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:402)     return printer(obj)
    [403](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:403) # Finally look for special method names
    [404](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:404) method = get_real_method(obj, self.print_method)

Cell In[1], [line 227](vscode-notebook-cell:?execution_count=1&line=227)
    [225](vscode-notebook-cell:?execution_count=1&line=225) @classmethod
    [226](vscode-notebook-cell:?execution_count=1&line=226) def formatter(cls, var, **kwargs):
--> [227](vscode-notebook-cell:?execution_count=1&line=227)     s = cls(var, **kwargs)
    [228](vscode-notebook-cell:?execution_count=1&line=228)     return s._repr_dw_()

Cell In[1], [line 221](vscode-notebook-cell:?execution_count=1&line=221)
    [218](vscode-notebook-cell:?execution_count=1&line=218) self.id = str(uuid.uuid4())
    [219](vscode-notebook-cell:?execution_count=1&line=219) pandas_df, conversion_method = api["pandas_transport"]["convert_to_pandas"](expr_val)
    [220](vscode-notebook-cell:?execution_count=1&line=220) tmp_vars[self.id] = {
--> [221](vscode-notebook-cell:?execution_count=1&line=221)     "converted": pandas_df.copy(deep=False), # create a shallow copy in case a displayed object is mutated in the same cell
    [222](vscode-notebook-cell:?execution_count=1&line=222)     "conversion_method": conversion_method
    [223](vscode-notebook-cell:?execution_count=1&line=223) }

AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by srdbk** [comment]
> In the latest Data Wrangler version, GeoPandas throws an error as soon as a geodata frame is displayed. Of course, this is a bit troublesome if you want to use Data Wrangler with Pandas, but also work on Geopandas projects at the same time. I currently have to deactivate the plugin depending on the project.
> 
> ```
> df = gpd.read_file('countries.geojson')
> df.head()
> ```
> 
> Error
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> File ~/Documents/projects/visuals-sommer-winterzeit-analyse/env/lib/python3.12/site-packages/IPython/core/formatters.py:402, in BaseFormatter.__call__(self, obj)
>     [400](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:400)     pass
>     [401](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:401) else:
> --> [402](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:402)     return printer(obj)
>     [403](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:403) # Finally look for special method names
>     [404](https://file+.vscode-resource.vscode-cdn.net/Users/x45f/Documents/projects/demo/src/~/Documents/projects/demo/env/lib/python3.12/site-packages/IPython/core/formatters.py:404) method = get_real_method(obj, self.print_method)
> 
> Cell In[1], [line 227](vscode-notebook-cell:?execution_count=1&line=227)
>     [225](vscode-notebook-cell:?execution_count=1&line=225) @classmethod
>     [226](vscode-notebook-cell:?execution_count=1&line=226) def formatter(cls, var, **kwargs):
> --> [227](vscode-notebook-cell:?execution_count=1&line=227)     s = cls(var, **kwargs)
>     [228](vscode-notebook-cell:?execution_count=1&line=228)     return s._repr_dw_()
> 
> Cell In[1], [line 221](vscode-notebook-cell:?execution_count=1&line=221)
>     [218](vscode-notebook-cell:?execution_count=1&line=218) self.id = str(uuid.uuid4())
>     [219](vscode-notebook-cell:?execution_count=1&line=219) pandas_df, conversion_method = api["pandas_transport"]["convert_to_pandas"](expr_val)
>     [220](vscode-notebook-cell:?execution_count=1&line=220) tmp_vars[self.id] = {
> --> [221](vscode-notebook-cell:?execution_count=1&line=221)     "converted": pandas_df.copy(deep=False), # create a shallow copy in case a displayed object is mutated in the same cell
>     [222](vscode-notebook-cell:?execution_count=1&line=222)     "conversion_method": conversion_method
>     [223](vscode-notebook-cell:?execution_count=1&line=223) }
> 
> AttributeError: 'NoneType' object has no attribute 'copy'
> ```

I have the same problem on my project.

**Comment by pwang347** [comment]
Hi folks! Thank you for alerting us to the issue, we've fixed the problem on our side and you can expect to see a new release version for it by Monday.

To disable the output viewer behaviour temporarily, you can find the following setting in VS Code config:

<img width="406" alt="Image" src="https://github.com/user-attachments/assets/ab3c17cc-397a-47eb-9b9e-498a1847594d" />

Apologies for any inconvenience caused by the above.

**Comment by simonhuwiler** [comment]
Phantastic, thanks for your work!

**Comment by pwang347** [comment]
Hi all, thank you for the patience! Just wanted to provide an update that the release with the fix for the issue above is now available in both versions 1.20.0 and 1.21.0 (pre-release). Please give it a try and let me know if you are still experiencing any issues with it. Hope this helps!

**Comment by philiporlando** [comment]
I've tried testing with Data Wrangler 1.20.1 and the pre-release 1.21.4 versions, but I'm unfortunately still unable to view GeoDataFrames. Any suggestions are appreciated!

Here's a sample dataset that I'm trying to view when using VS Code's debug mode:
```python
import geopandas as gpd
import pandas as pd

# Sample data
data = {
    "id": [1, 2, 3, 4, 5],
    "name": ["A", "B", "C", "D", "E"],
    "latitude": [45.5231, 45.5232, 45.5233, 45.5234, 45.5235],
    "longitude": [-122.6765, -122.6766, -122.6767, -122.6768, -122.6769],
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert to GeoDataFrame using points_from_xy
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df["longitude"], df["latitude"]), crs="EPSG:4326"
)

print(gdf)
```

**Comment by pwang347** [comment]
Hi @philiporlando, apologies for the late reply! Unfortunately I can confirm that viewing GeoDataFrames (even just the data, without visualizations/explore as mentioned above) is not currently supported. The pre-release comment above was for an issue where an extra error message was appearing in the output.

To provide some more context on this current challenge/limitation, a good portion of our launch points (including debugger for .ipynb and .py files) are currently coming from the Jupyter extension. To support GeoPandas for these scenarios we would need "GeoDataFrame" to be added to the list of detectable types in this [list](https://github.com/microsoft/vscode-jupyter/blob/6d82cc6511220ae1ebb381288c17969247b183e7/package.json#L2042-L2051). I think the preferred approach to scale better for other future data types though would be to make it more flexible to show a launch button based on some dynamic condition like commented in https://github.com/microsoft/vscode-jupyter/issues/15853.

Hope this helps!

**Comment by philiporlando** [comment]
@pwang347, thank you for this context. I agree that something like https://github.com/microsoft/vscode-jupyter/issues/15853 would be preferred.
